name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Create ZIP file
        run: |
          cd dist
          zip -r ../carboncommander-extension.zip *
          cd ..
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: carboncommander-extension.zip
          draft: false
          prerelease: false
          generate_release_notes: true 